FROM bh.cr/balenablocks/bluetooth-%%BALENA_ARCH%%

WORKDIR /usr/src

COPY rtl8761b_fw.bin lib/rtl8761b_fw.bin
COPY rtl8761b_config.bin lib/rtl8761b_config.bin

COPY start.sh /usr/src/
CMD [ "/bin/bash", "/usr/src/start.sh" ]